src/pages/ethereum.js

Removed additional "or" in the list of use-cases in paragraph 2

Removed additional "or" in the list of use-cases in paragraph 2

---

src/pages/about/index.js

Incorporated Joe's suggested changes

Incorporated Joe's suggested changes

---

src/components/Footer.js
src/components/Layout.js

Fix hidden content when footer is open
#24

Fix hidden content when footer is open

---

src/components/SharedStyledComponents.js
src/components/layout.css

Update body font styles

---

src/components/Constellation.js

Add links to constellation stars
#32

Add links to constellation stars

---

src/components/Constellation.js

Refactor constellation links to align with SVG
#32

Link star sync

---

src/components/Layout.js

Close footer only on user scroll [Fixes #37]

---

src/components/Layout.js
src/components/layout.css

Prevent overscroll (for Chrome/FF/Opera):
https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior
#39

Prevent overscroll [Fixes #39]

---

src/components/Constellation.js

Adjust mobile landscape [Fixes #31]

---

src/components/Layout.js

Refresh on device orientation change
#30

Refresh on orientationchange [Fixes #30]

---

package.json
src/components/Profile.js
src/components/layout.css
src/pages/about/board.js
yarn.lock

Add board Twitter links

---

src/components/Footer.js

Update to ethereum.org/en/cookie-policy/
#57

Update cookie policy link

---

src/components/Footer.js
src/pages/index.js

Add homepage link to PDF report
#59

Add homepage link to report

---

src/pages/index.js

new top bar design

---

src/pages/about/board.js

Update name to correct spelling.
None - surfaced via email.

Fix Patrick's name

---

index.css

Fix for the scrollbar that appears on the main container on the homepage when the user scrolls down.
Fixes #67

fix scrollbar on homepage

---

assets/ETH-loading.svg
index.css

A new loading image was created using SVG.

A new loading image created

---

infinitegarden.html

We forgot the 'r' in Nurturing!

Fix typo in Infinite Garden page

---

src/components/nav/Nav.tsx

Disable prefetch for large pdf file RE: discussion with @tomosaito

No pdf prefetch

---

src/components/footer/Footer.module.scss
src/components/footer/Footer.tsx

Footer fix to move the scroll icon out of <footer>.

Footer fix to move the scroll icon out of <footer>

---

.gitignore
src/components/footer/Footer.module.scss
src/components/footer/Footer.tsx
src/components/page/Content.tsx
src/styles/global.scss
src/utils/useScrollDirection.ts

Clicking the scroll indicator now scrolls the content into view. Also updated the accompanying text to reflect this, as well as make it clearer that you should tap or swipe instead of click or scroll when on device with no pointer (like a phone). 
cc @tomosaito

Improve UX RE: scroll to show content

---

src/components/footer/Footer.module.scss
src/components/footer/Footer.tsx

This commit removes a section of the footer as we have received a voluntary enquiry from a state authority that included a requirement for confidentiality.

Remove footer text

---

src/app/ef/page.tsx

Per comms and legal, updating from Foundation Council to Ethereum Foundation Board

Foundation Council > Ethereum Foundation Board

---

src/app/ef-social-requests/head.tsx
src/app/ef-social-requests/page.tsx
src/components/nav/Nav.tsx
src/components/page/animate.js

Social requests page
